{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian-generator-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "wtgsfsjf5jdpfpz63mdu5uww4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-generator-api-1.0.0.jar",
          "url": "laplacian-generator-api-1.0.0.jar",
          "size": 62467,
          "sha512": "07ba224962f8f87fd33c910571442b9d49727351db06913de3209d4c76eadfdae0af96eed3e492924537af04bc386bc6d0555740bc4122005965f10691468379",
          "sha256": "9c1a25ac8434c3bf465751d5ce346ee87b56e824ace1a508da9061ea721a3bcb",
          "sha1": "137443ccb557db798470072f3adffcf6e99b3d89",
          "md5": "b14ac80a38f231f0bbeb885d4c908313"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "org.atteo",
          "module": "evo-inflector",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.github.javafaker",
          "module": "javafaker",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-generator-api-1.0.0.jar",
          "url": "laplacian-generator-api-1.0.0.jar",
          "size": 62467,
          "sha512": "07ba224962f8f87fd33c910571442b9d49727351db06913de3209d4c76eadfdae0af96eed3e492924537af04bc386bc6d0555740bc4122005965f10691468379",
          "sha256": "9c1a25ac8434c3bf465751d5ce346ee87b56e824ace1a508da9061ea721a3bcb",
          "sha1": "137443ccb557db798470072f3adffcf6e99b3d89",
          "md5": "b14ac80a38f231f0bbeb885d4c908313"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "laplacian-generator-api-1.0.0-sources.jar",
          "url": "laplacian-generator-api-1.0.0-sources.jar",
          "size": 13629,
          "sha512": "82a65289a2e2cdb2a185d87c543cbf98f9c8c829bf7f39de630a4e0142e824919a6f96015f4922f11c3b6419171d63eb664492e1a5b6863cb8576eca3ec734be",
          "sha256": "0e967b45c780bc721741182ca053393d4d43b1dd89ea23e93e51e52d8a97117a",
          "sha1": "56efbc9c492e99d6ead02c6ca096043ead598be6",
          "md5": "b03a0daa0a3de0629b358727cecbf804"
        }
      ]
    }
  ]
}
